packages:
  - apps/*
  - packages/*

catalog:
  lodash: 4.17.21
  tailwindcss: 4.1.17
  "@fortawesome/fontawesome-svg-core": 7.1.0
  "@fortawesome/free-brands-svg-icons": 7.1.0
  "@fortawesome/free-regular-svg-icons": 7.1.0
  "@fortawesome/free-solid-svg-icons": 7.1.0
